#配置服务器
server:
  port: 8100
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /customer_service



#配置数据库
spring:
  datasource:
    username: huize
    password: huizekeji.
    url: jdbc:mysql://39.108.232.17:3306/enter_customer_service?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙


  redis:
    host: 39.108.232.17
    port: 6379
    password: 838860376abc
    timeout: 5000
    database: 1

  http:
    encoding:
      charset: UTF-8
      enabled: true

dubbo:
  application:
    name: enter-service
    qos-port: 28888
  registry:
    address: redis://39.108.232.17:6379
    username: root
    password: 838860376abc
  protocol:
    name: dubbo
    port: 12143
  scan:
    base-packages: com.enter.service

#配置日志
logging:
  level:
    com.enter.print: info
  path: ./log
  file: customer-service.log
debug: false

#通用mapper
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true
  enum-as-simple-type: true
  # catalog: print
  safe-delete: true